name: Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}
      - name: Install Dependencies
        run: npm install
      - name: Mocha Tests
        run: npm run test:reportJson
      - name: Coverage
        run: npm run coverage:report
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: 'Mocha Tests'
          reporter: 'mocha-json'
          path: './mocha-report.json'
      - name: Coverage Report
        uses: sidx1024/report-nyc-coverage-github-action@v1.2.6
        with:
          coverage_file: 'coverage/coverage-summary.json'
  eslint:
    runs-on: ubuntu-latest
    name: Run ESlint
    permissions:
      contents: read
      pull-requests: write
    steps:
     - uses: actions/checkout@v2
     - id: nvmrc
       uses: browniebroke/read-nvmrc-action@v1
     - uses: actions/setup-node@v3
       with:
         node-version: ${{ steps.nvmrc.outputs.node_version }}
     - uses: reviewdog/action-eslint@v1
       with: 
         github_token: ${{ secrets.GITHUB_TOKEN }}
         reporter: github-pr-review
  coverage:
    runs-on: ubuntu-latest
    name: Coverage assessment
    steps:
      - uses: actions/checkout@v2
      - name: Coverage
        run: npm run coverage:report
      - uses: actions/setup-node@v3
        with:
          node-version: 14
